# config/app.yml for rails-settings-cached
defaults: &defaults
  redis:
    url: "redis://127.0.0.1:6379/0"
    sidekiq: "redis://127.0.0.1:6379/1"
  token_expire_time: 604800 # 7 * 24 * 3600
  sms:
    mw:
      submit_url: "http://127.0.0.1:8901/MWGate/wmgw.asmx"
      userid: "1"
      password: "1"


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
