# source 'https://rubygems.org'
source 'http://gems.ruby-china.org'

# git_source(:github) do |repo_name|
#   repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
#   "https://github.com/#{repo_name}.git"
# end
gem 'sidekiq'
gem "mini_magick"
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.3'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'rails-i18n', '~> 5.0.0'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
gem "dalli"

gem 'bootstrap-sass'
gem 'kaminari'
gem "select2-rails"
gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.14.30'
gem 'carrierwave'
gem 'fastdfs-client'
gem 'uuidtools'
gem 'tinymce-rails'
gem 'tinymce-rails-langs'
gem 'cancancan', '~> 1.10'
gem 'elasticsearch'
gem "audited", "~> 4.5"
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 3.0'
gem "redis-namespace"
gem 'whenever', :require => false #定时任务
gem 'my_alipay', '~> 0.3.5'
gem "unicorn-worker-killer"
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
# Use Unicorn as the app server
gem 'unicorn'
gem "oneapm_rpm"
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  gem "pry"
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem "capistrano", "~> 3.7"
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-bundler', '~> 1.1.0'
  gem 'capistrano-rvm', '~> 0.1.2'
  gem 'capistrano3-unicorn', '~> 0.2.0'# Add this if you're using rbenv# gem 'capistrano-rbenv', '~> 2.0.0'
  gem 'capistrano-sidekiq'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'ransack'
gem 'rest-client', '~> 2.0', '>= 2.0.2'
gem "roo", "~> 2.7.0"
