default: &default
  appid: "1" #跟单高手_dev
  secret: "1" #跟单高手_dev
  token:  "2"
  access_token: "/var/tmp/wechat_access_token"
  jsapi_ticket: "/var/tmp/wechat_jsapi_ticket"

production:
  <<: *default

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default

# Multiple Accounts
#
# wx2_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token2"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket2"
#
# wx2_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx2_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token3"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket3"
#
# wx3_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
