source 'http://gems.ruby-china.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'mysql2'
gem 'composite_primary_keys', git: "https://github.com/composite-primary-keys/composite_primary_keys.git"

gem 'jpush'

gem 'whenever', :require => false #定时任务
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.2'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'unicorn'
gem 'unicorn-worker-killer'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'rails-i18n'
gem 'http_accept_language'
gem 'jquery-atwho-rails'

# 上传组件
gem 'carrierwave'

# Lazy load
gem 'mini_magick'

# 验证码
gem 'rucaptcha'

#微信api
gem 'wechat'

#搜索
gem 'ransack'

# 赞、关注、收藏、屏蔽等功能的数据结构
gem 'action-store'

# 分页
gem 'will_paginate'

# Permission
gem 'cancancan'

# Redis
gem 'redis'
gem 'redis-namespace'

# Cache
gem 'second_level_cache'

# Setting
gem 'rails-settings-cached'

# 队列
gem 'sidekiq'


# 表单
# gem 'simple_form'

# Dalli
gem 'dalli'

#异常记录
# gem 'exception-track'

gem 'status-page'

#api文档管理
gem 'sdoc', '1.0.0.rc1'
gem 'yard'
gem 'migration_comments'
gem 'kramdown', :groups => [:development], :require => false


gem 'faraday'

gem 'nokogiri'

#mongo
gem 'mongo'
gem 'eventmachine'
gem 'websocket-eventmachine-client'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem "capistrano", "~> 3.7"
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-bundler', '~> 1.1.0'
  gem 'capistrano-rvm', '~> 0.1.2'
  gem 'capistrano3-unicorn', '~> 0.2.0'
  gem 'annotate', :path => "vendor/annotate-2.7.2"
  gem 'pry'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
