development:
  fastdfs:
    secret_key: '1'
    tracker_server: '127.0.0.1'
    port:  '22122'
    tracker_url: 'http://127.0.0.1:8888'
#测试环境
production:
  fastdfs:
    secret_key: '1'
    tracker_server: '127.0.0.1'
    port:  '22122'
    tracker_url: 'http://127.0.0.1:8888'


